extends:
  - "eslint:recommended"
  - "plugin:import/typescript"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parserOptions:
  project: './tsconfig.json'
rules:
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"