version: "3.7"

# TODO only use docker-compose for db (node foreman for api / frontend dev)
services:
  api:
    build:
      context: ./api
    depends_on:
      - database
    ports:
      - "5000:5000"
    volumes:
      - ./api/src:/app/src
    environment:
      - CORS_ORIGINS=http://localhost:4200
      - PORT=5000
      - POSTGRES_HOST=database
      - SESSION_SECRET=test

  database:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cyvasse-user
      - POSTGRES_PASSWORD=test
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./frontend/src:/app/src
  
volumes:
  postgres-data: