version: "3.7"

services:

  database:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cyvasse-user
      - POSTGRES_PASSWORD=test
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
  
volumes:
  postgres-data:
  redis-data: