version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependencies-root-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: dependencies-api-{{ checksum "api/yarn.lock" }}
      - restore_cache:
          key: dependencies-frontend-{{ checksum "frontend/yarn.lock" }}
      - run: yarn install
      - run: cd api && yarn install
      - run: cd frontend && yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-root-{{ checksum "yarn.lock" }}
      - save_cache:
          paths:
            - api/node_modules
          key: dependencies-api-{{ checksum "api/yarn.lock" }}
      - save_cache:
          paths:
            - frontend/node_modules
          key: dependencies-frontend-{{ checksum "frontend/yarn.lock" }}
      - run: yarn lint
      - run: cd api && yarn build
      - run: cd frontend && yarn test