common: &common
  adapter: postgresql

development:
  <<: *common
  host: 127.0.0.1
  database: cyvasse_development

test:
  <<: *common
  host: 127.0.0.1
  database: cyvasse_text

production:
  <<: *common
  database: cyvasse_production
