# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: chily-user
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.15
          cache: 'yarn'
      - name: Install top level dependencies
        run: yarn --frozen-lockfile
      - name: Install api dependencies
        run: cd api && yarn install --frozen-lockfile
      - name: Install frontend dependencies
        run: cd frontend && yarn install --frozen-lockfile
      - name: Copy shared code
        run: make copy-shared
      - name: Lint
        run: yarn lint
      - name: Prettier check
        run: yarn prettier --check
      - name: Build API
        run: cd api && yarn build
      - name: Test API
        run: cd api && yarn create-databases && yarn test
        env:
          NODE_ENV: ci
          DATABASE_URL: 'postgres://chily-user:test@postgres/chily-test'
          REDIS_URL: 'redis://redis:6379'
      - name: Test Frontend
        run: cd frontend && yarn test
      - name: Build production image
        run: docker build .
